services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    # https://github.com/redis-stack
    # RedisJSON, RediSearch, RedisTimeSeries, and RedisBloom
    image: 'redis/redis-stack-server:latest'
    ports:
      - '6379'
