apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyurl-prometheus-config
  
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'tinyurl-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'tinyurl-app-service:8080' ]


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyurl-prometheus
  
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyurl-prometheus
  template:
    metadata:
      labels:
        app: tinyurl-prometheus
    spec:
      containers:
        - name: tinyurl-prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: tinyurl-prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: tinyurl-prometheus-service
  
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: tinyurl-prometheus
