# Primary PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Replica PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ConfigMap for postgres configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  primary.conf: |
    listen_addresses = '*'
    max_connections = 100
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
  replica.conf: |
    hot_standby = on
    primary_conninfo = 'host=postgres-primary-service port=5432 user=replicator password=replpass'
---
# Primary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-primary
  labels:
    app: postgres
    role: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: primary
  template:
    metadata:
      labels:
        app: postgres
        role: primary
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_REPLICATION_USER
              value: "replicator"
            - name: POSTGRES_REPLICATION_PASSWORD
              value: "replpass"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: primary.conf
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-primary-pvc
        - name: postgres-config
          configMap:
            name: postgres-config
---
# Replica Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica
  labels:
    app: postgres
    role: replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              value: "secret"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: replica.conf
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-replica-pvc
        - name: postgres-config
          configMap:
            name: postgres-config
---
# Primary Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-service
spec:
  selector:
    app: postgres
    role: primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# Replica Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-service
spec:
  selector:
    app: postgres
    role: replica
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
